### ISSUE TITLE
POO1 -MODELAGEM DE CLASSE EXERCÍCIO 3 - MODELAGEM CARRO

### ISSUE THREAD

**Issue by MarcioZup** [GuillaumeFalourd/java-exercices#13]
[Exercício escolhido para resolução](https://github.com/GuillaumeFalourd/java-exercices/blob/main/1-POO1/3-modelagem-de-classe.md)

**Comment by GuillaumeFalourd** [comment]
Olá @MarcioZup, tem 4 TODOS nesse arquivo. Qual dos 4 quer resolver?
