### ISSUE TITLE
0 Básico - Estrutura Sequencial -  Exercicio 8: Calculo Salarial

### ISSUE THREAD

**Issue by dorayenCarrasquel** [GuillaumeFalourd/java-exercices#27]
[0 Básico - Estrutura Sequencial -  Exercicio 8 ](https://github.com/GuillaumeFalourd/java-exercices/blob/main/0-BASICO/1-estrutura-sequencial.md)

**Faça um Programa que receba o quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês, sabendo-se que são descontados 11% para o Imposto de Renda, 8% para o INSS e 5% para o sindicato, faça um programa que nos dê respectivamente:**
* Salário bruto.
* Quanto pagou ao INSS.
* Quanto pagou ao sindicato.
* Qual o salário líquido do funcionário.

**Comment by GuillaumeFalourd** [comment]
Resolvido com https://github.com/GuillaumeFalourd/java-exercices/pull/37
