### ISSUE TITLE
 Aquecimento POO1 Exercises -  Exercício 3 

### ISSUE THREAD

**Issue by M4r1-D3v** [GuillaumeFalourd/java-exercices#4]
Irei fazer o seguinte exercício:

3.Crie um programa para gerenciar o cardápio de um restaurante. Cada prato tem um nome e pode conter diversos ingredientes. No final do programa, o usuário deve decidir se irá adicionar mais de um prato, exibir todos os pratos cadastrados ou excluir um prato pelo nome.

**Comment by GuillaumeFalourd** [comment]
Obrigado por abrir a ISSUE Mariana. Assinei ela para você. Fico no aguardo da sua contribuição 🚀

**Comment by M4r1-D3v** [comment]
> Obrigado por abrir a ISSUE Mariana. Assinei ela para você. Fico no aguardo da sua contribuição 🚀

Desculpa, esqueci de colocar a Label 😬, obrigada 😉

**Comment by GuillaumeFalourd** [comment]
Resolvido com https://github.com/GuillaumeFalourd/java-exercices/pull/14
