### ISSUE TITLE
Exercício 1 - Aquecimento - POO1

### ISSUE THREAD

**Issue by yan-rds** [GuillaumeFalourd/java-exercices#5]
Irei fazer o primeiro exercício do Aquecimento - POO1

1.Crie um programa para gerenciar uma lista de produtos de um estabelecimento, cada produto tem um nome e um preço. No final do programa, o usuário deve decidir se irá adicionar mais de um produto, exibir todos os produtos cadastrados ou excluir um produto pelo nome.[Exercício 1](https://github.com/GuillaumeFalourd/java-exercices/blob/main/1-POO1/1-aquecimento.md)

(não consegui adicionar a label)

**Comment by GuillaumeFalourd** [comment]
Obrigado @yan-rds , assinei essa ISSUE para você 🙂😁
